default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: budget_manager

test:
  <<: *default
  database: budget_manager_test

